delete from user;
delete from actor;
delete from actor_class;
delete from actor_item;
delete from actor_item_ammo;
delete from actor_skill;
delete from actor_effect;
delete from auction_bid;
delete from auction_bid_item;
delete from auction_sale;
delete from auction_sale_item;
delete from building_progress;
delete from clan;
delete from clan_actor;
delete from clan_application;
delete from clan_capture;
delete from clan_invitation;
delete from clan_relation;
delete from clan_stronghold;
delete from event;
delete from event_thread;
delete from pdata;
delete from user_mod;
delete from user_priv_mapedit;
alter table actor auto_increment = 1;
alter table actor_item auto_increment = 1;
alter table actor_item auto_increment = 1;
alter table auction_bid auto_increment = 1;
alter table auction_sale auto_increment = 1;
alter table clan auto_increment = 1;
alter table event auto_increment = 1;
alter table event_thread auto_increment = 1;
alter table user auto_increment = 1;
update map_cell set tile = base_tile where tile = 23;
update building set owner = null, hp = 5 where owner != null;
